version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 14
      semver-patch-days: 14
      semver-minor-days: 14
      semver-major-days: 30
    groups:
      pip-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      pip-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - python
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions-version-updates:
        applies-to: version-updates
        patterns:
          - "*"
      github-actions-security-updates:
        applies-to: security-updates
        patterns:
          - "*"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
